language: java

jdk:
- openjdk8
env:
- SONAR_VERSION=
- SONAR_VERSION=7.3
- SONAR_VERSION=7.5
matrix:
  allow_failures:
  - env: SONAR_VERSION=7.5

script:
- if [ "$SONAR_VERSION" ]; then mvn verify -B -V -e -Dsonar.version=$SONAR_VERSION; else mvn verify -B -V -e; fi

dist: xenial

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
